# Site settings
title: 
subtitle:
email:
description: A SET OF FULLY OBSERVABLE MICROSERVICES (WIP)
baseurl: /
url: "" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/flam-flam
gitlab_url:
googleplus_url:
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
